name: wait-for-check-action
description: Wait for a check (ie. an action job) to complete before proceeding
author: pentible
branding:
  icon: clock
  color: gray-dark

runs:
  using: node20
  main: dist/index.js

# TODO: Define inputs
inputs:
  check-name:
    description: Your input description here
    required: true

# TODO: Define outputs
outputs:
  time:
    description: Your output description here
